defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
    address=":8080"
    [entryPoints.api.tls]
    [entryPoints.api.auth]
      [entryPoints.api.auth.basic]
        users = [
          "<traefik_admin_username>:<traefik_admin_password>",
        ]

[api]
  entrypoint="api"

[acme]
  email = "admin@example.com"
  storage = "/etc/traefik/acme.json"
  entryPoint = "https"
  acmeLogging = true
  [acme.tlsChallenge]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "<public_hostname>"
  watch = true

[[acme.domains]]
  main = "<public_hostname>"

logLevel = "INFO"

[traefikLog]
  filePath = "/var/log/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/var/log/access.log"
  format = "json"
